### ISSUE TITLE
[Question] Map panning to left mouse button

### ISSUE THREAD

**Issue by hailstorm75** [miroiu/nodify#103]
I want to allow users to pan within the node editor using the left mouse button.

![image](https://github.com/miroiu/nodify/assets/16069996/8fcd63eb-0c85-4bc3-a6cb-6973caf46da6)

Similarly to, e.g., Blender's tool selection that modifies what the left mouse button does, I wish to introduce three tools for operating the node editor:
 - Select - the default
 - Move - left click + drag pans the editor
 - Delete - clicking or select+release deletes items

![image](https://github.com/miroiu/nodify/assets/16069996/63e391cb-53c9-43bc-812c-5e286bd3fafe)

I've found that the `EditorGestures` class is public; thus, it is possible to modify the default gestures to something custom.

However, I couldn't figure out how to detach the selection from the left click.

I've tried the following:
```csharp
EditorGestures.Selection.DefaultMouseAction = MouseAction.None;
EditorGestures.Selection.Replace = new MouseGesture(MouseAction.None);
EditorGestures.Selection.Remove = new MouseGesture(MouseAction.None);
EditorGestures.Selection.Append = new MouseGesture(MouseAction.None);
EditorGestures.Selection.Invert = new MouseGesture(MouseAction.None);

EditorGestures.Pan = new MultiGesture(MultiGesture.Match.Any, new MouseGesture(MouseAction.LeftClick), new MouseGesture(MouseAction.MiddleClick));
```
Could you please point me in the right direction?

Given how these gestures are implemented, I'd assume it should be fine to modify them during the runtime.
Is that correct?

**Comment by miroiu** [comment]
Hi! You should be able to modify the gestures at runtime, however it seems that the select gesture property is missing the setter. I'll create a PR to address that. Do you build from the source code or from the nuget package?

**Comment by hailstorm75** [comment]
I use the NuGet package

**Comment by miroiu** [comment]
I created the PR and, it looks like not all the gestures were customizable at runtime, especially the ones used for the `EditorCommands`. Therefore it resulted in more work than expected. Could you please let me know if this suits your needs? I'm open to suggestions and ideas. #104

**Comment by hailstorm75** [comment]
Based on the description of the PR, this looks perfect. I shall do some testing today and let you know.

**Comment by miroiu** [comment]
I merged the PR and will push a new release to NuGet soon. Please feel free to reopen the issue if needed.
