### ISSUE TITLE
[Bug] Knot not working well with new step connection style, also with backward connection directions (right -> left, bottom -> up) in general

### ISSUE THREAD

**Issue by hendrikp** [miroiu/nodify#110]
Firstly the new step connection is a great addition, however i noticed that with the knot it leads to even more strange looking connections then the knot had before.

**Describe the bug**

Case A: enabled step connection for pretty normal knot placement (same orientation all connectors)

![image](https://github.com/miroiu/nodify/assets/130550/27c11d31-5c4f-4b5c-8e13-6e451b602134)

Case B: connections pointing backward in different linestyles (same orientation all connectors)

![image](https://github.com/miroiu/nodify/assets/130550/56ac81cc-ebf1-4135-93b5-5e2b337fc857)

![image](https://github.com/miroiu/nodify/assets/130550/d9f2f0dd-3e88-4e5f-b7bd-eb966fc29527)

![image](https://github.com/miroiu/nodify/assets/130550/d09ac7b6-1229-48de-b41d-5d62652d3f81)

B with step: in this case the step even goes through the node, i think it should like the other connections styles first go a bit to the right likely.
![image](https://github.com/miroiu/nodify/assets/130550/fbc6bf23-e5db-422d-b6a2-c73f91249d35)

**To Reproduce**
See screenshots

**Expected behavior**
The knot input/output should not be on same side and should be based on the actual direction the input is coming from not based on the connector.

Possibly the knot can be fixed for those cases to not expect input to be left or top, but dynamically adjusting itself to the actual connection direction.

Also in general it would be good that placing a knot never causes a connection to cross/loop with itself.

**Comment by miroiu** [comment]
I created a PR to fix this issue, and also added vertical orientation for knot nodes. I'm considering removing Direction and Orientation from connections and adding SourcePosition and TargetPosition instead. This way we can have this type of flow for all connection styles:

![image](https://github.com/miroiu/nodify/assets/12727904/01649435-37d4-47ba-9712-561a2e85bfa1)

As you can see in the picture above there's still an issue with the connector offset when both connectors have the same position. This is because the offset is currently calculated based on Direction and Orientation.

 Please let me know if we can close this issue.

**Comment by hendrikp** [comment]
hm yeah i have the orientation for my playground actually not on the Block, but on the Ports themselves (because some Blocks can have a mix of vertical and horizontal connections),

For the knots themselves the approach you showed seems good. 

Also i think in general it would be good for the connections control points that they maybe take the target/source block size into account so that they dont go through their associated blocks

I will test now.

**Comment by hendrikp** [comment]
For reference thats how im doing it on the knotviewmodel, i have an OnUpdateLayout function there that is called when something disconnects/connects to the knot.

```
    public class KnotViewModel ....
    {
....
        public override void OnUpdateLayout()
        {
            base.OnUpdateLayout();

            // Check if vertically oriented 
            var startVertical = Connector.Connections.FirstOrDefault(c =>
                c.Input.Orientation == Orientation.Vertical && c.Input.Node != this);

            if (startVertical != null)
            {
                Connector.Orientation = Orientation.Vertical;
            }
            else
            {
                Connector.Orientation = Orientation.Horizontal;
            }
        }
```

**Comment by miroiu** [comment]
> I'd recommend also to remove Orientation from Nodes, and move it to Connector, or having it in both places, but the Nodes one being more of a hint for the node generator/display of the playground sample itself

I may consider doing this in the future, but for now, I find the playground app to be good enough for testing new features
