### ISSUE TITLE
Can you provide a minimal example

### ISSUE THREAD

**Issue by yaobus** [miroiu/nodify#116]
Can you provide a minimal example? The current three examples are a bit confusing for beginners who are new to this project. It would be great if you could provide an example to demonstrate a single function，thanks！！

**Comment by miroiu** [comment]
Hi, please check out the new Example/Shapes application.

**Comment by yaobus** [comment]
OK，thanks！

**Comment by yaobus** [comment]
I am a beginner with a very poor foundation. Do you have any more basic cases? The existing cases are still a bit complicated for me

**Comment by miroiu** [comment]
There's a minimal example in the wiki: https://github.com/miroiu/nodify/wiki/Getting-Started#a-minimal-example
