### ISSUE TITLE
Whether the intersection of solid lines in the circuit diagram can be realized？

### ISSUE THREAD

**Issue by jinleil** [miroiu/nodify#118]

**Comment by jinleil** [comment]
![image](https://github.com/miroiu/nodify/assets/44106819/a8794c66-64f1-4fa4-999e-043446123d49)

**Comment by miroiu** [comment]
The `KnotNode` in the Playground application does a similar thing (double click a connection wire to split):

![image](https://github.com/miroiu/nodify/assets/12727904/39aa8d47-7d7d-48e1-a4dc-4a13be81e86f)

**Comment by jinleil** [comment]
Thank you. I'll try

**Comment by miroiu** [comment]
Feel free to reopen this issue if you have any questions.
