### ISSUE TITLE
How to Implement Graphical Nodes Similar to FastGPT in a Node Project

### ISSUE THREAD

**Issue by zt199510** [miroiu/nodify#123]
Hello,
﻿
Once again, I need to trouble you for some assistance. I am working on a Workflow project and have encountered some challenges that I hope you can help me with. The project involves implementing functionalities similar to graphical nodes in a flowchart, as shown in the attached image.
﻿
I have encountered an issue in Nodify.Shapes. I see that there are 4 connectors, but I am at a loss about how to create a new Out connector on the right side. Could you please provide some guidance on how to achieve this?
﻿
Thank you very much for your help!

![72c82ccb-e6cf-4266-bff4-0dab10639b2d](https://github.com/user-attachments/assets/4eac9c43-60a7-44b5-b370-a6bd22a32fd6)

**Comment by zt199510** [comment]
I really enjoy this type of UI design, but I found it quite challenging when I started working on it. 😅

**Comment by miroiu** [comment]
Hi,

You can use a `StackPanel` to add more connectors on any side.

```xml

<StackPanel DockPanel.Dock="Right" VerticalAlignment="Center">
    <nodify:Connector DataContext="{Binding RightConnector}"
                        Anchor="{Binding Anchor, Mode=OneWayToSource}"
                        HorizontalContentAlignment="Right"
                        Margin="0 0 -11 10"
                        Visibility="Hidden"
                        Height="Auto"
                        Width="25"
                        x:Name="RightConnector" />
    <nodify:Connector DataContext="{Binding RightConnector2}"
                        Anchor="{Binding Anchor, Mode=OneWayToSource}"
                        HorizontalContentAlignment="Right"
                        Margin="0 0 -11 0"
                        Visibility="Hidden"
                        Height="Auto"
                        Width="25"
                        x:Name="RightConnector2" />
</StackPanel>
```

![image](https://github.com/user-attachments/assets/8026a531-7691-4816-9e7f-94a552d96b32)

Is this what you are having trouble with?

**Comment by zt199510** [comment]
Thank you. Could you provide some insights or a detailed approach on how to implement a feature similar to a bird's-eye view?

**Comment by miroiu** [comment]
Do you mean a minimap?

**Comment by miroiu** [comment]
I created a PR that adds a Minimap control to the library #124

**Comment by zt199510** [comment]
Thank you
