### ISSUE TITLE
[Question] DelegateCommand could not be found

### ISSUE THREAD

**Issue by handrake0724** [miroiu/nodify#125]
Hi,

I am new to nodify and c# so it might be likely that the issue I have now is trivial.
I am following the minimal example written in the documentation.
To implement pending connections, the following codes were given.
```
public class PendingConnectionViewModel
{
    private readonly EditorViewModel _editor;
    private ConnectorViewModel _source;

    public PendingConnectionViewModel(EditorViewModel editor)
    {
        _editor = editor;
        StartCommand = new DelegateCommand<ConnectorViewModel>(source => _source = source);
        FinishCommand = new DelegateCommand<ConnectorViewModel>(target =>
        {
            if (target != null)
                _editor.Connect(_source, target);
        });
    }

    public ICommand StartCommand { get; }
    public ICommand FinishCommand { get; }
}
```

but compileation says DelegateCommand is not found.

At first, I used nodify from Nuget package but tried also the dll file from source compile. All the efforts was fruitless.

I want to know how to solve this issue.

**Comment by miroiu** [comment]
Hi, I updated the wiki to include the `DelegateCommand` implementation.

**Comment by handrake0724** [comment]
Thank you so much. It works and I close the issue.
