### ISSUE TITLE
[Question] How to detect whether two Connections intersect or are close enough?

### ISSUE THREAD

**Issue by Summpot** [miroiu/nodify#134]
I would like to implement this effect in StepConnection or CircuitConnection.
![image](https://github.com/user-attachments/assets/d7dcbc4f-6fdf-41c2-bc15-d7a6b14cf058)
I also want a certain segment of the StepConnection to be draggable in the direction perpendicular to the line, and to prevent any draggable segments of two StepConnections from overlapping.
It all seems to require detecting if the lines intersect or are close enough. However, I don't see any good way to get the actual path of the line. Does anyone have any suggestions? Thanks!

**Comment by miroiu** [comment]
Hi, sorry for no response. While I believe it is possible to implement this functionality, I can't think of a simple or an efficient solution. It may be better just implementing a custom connection type from search.

**Comment by Summpot** [comment]
Thanks to your reply, I have implemented a StepSonnection that can be dragged through some vector operations and rewrite the logic of drawing geometry.
