### ISSUE TITLE
[Feature] Allow more complexe gestures

### ISSUE THREAD

**Issue by ndegheselle** [miroiu/nodify#146]
Hi, would like to have more customizable / complexe gestures for states.

Problem :
Users are used to the navigation of softwares like photoshop or paint.net and want the same feel (`Ctrl + Scroll` = zoom, `Left Click + Space` = Pan, `Scroll` = Pan vertically, `Scroll + Shift` = Pan horizontally).

Solution :
Allow more complexe gestures on states : 
- Mix mouse and keyboard events (for  `Left Click + Space`)
- Separate handling of vertical and horizontal panning

Here is a fork [feature/extended-gestures](https://github.com/miroiu/nodify/compare/master...ndegheselle:nodify:feature/extended-gestures?expand=1) where I did one possible implementation of that, there is still some things that could be checked :
- Handling panning with keyboard
- Regroup the pan vertical / horizontal gestures like the SelectionGestures

_Unrelated in the fork_ : I also added custom cursors for panning which is unrelated but would be cool

**Comment by miroiu** [comment]
Hi, the following code allows zooming with `Ctrl + Scroll` and panning with `Space + Left Click` in the playground app:

<details>
<summary>Click to expand code block</summary>

```csharp
 public partial class NodifyEditorView : UserControl
 {
     public NodifyEditor EditorInstance => Editor;

     private EditorGestures DefaultEditorGestures { get; set; }

     public NodifyEditorView()
     {
         InitializeComponent();

         DefaultEditorGestures = new EditorGestures();
         DefaultEditorGestures.Editor.ZoomModifierKey = ModifierKeys.Control;

         EditorGestures.Mappings.Apply(DefaultEditorGestures);
     }

     private void Minimap_Zoom(object sender, ZoomEventArgs e)
     {
         EditorInstance.ZoomAtPosition(e.Zoom, e.Location);
     }

     protected override void OnKeyDown(KeyEventArgs e)
     {
         if (e.Key == Key.Space)
         {
             EditorGestures.Mappings.Apply(PanningGestureMappings.Instance);

             Cursor = Cursors.Hand;
         }
     }

     protected override void OnKeyUp(KeyEventArgs e)
     {
         if (e.Key == Key.Space)
         {
             EditorGestures.Mappings.Apply(DefaultEditorGestures);

             Cursor = Cursors.Arrow;
         }
     }
 }

 internal class PanningGestureMappings : EditorGestures
 {
     public static readonly PanningGestureMappings Instance = new PanningGestureMappings();

     public PanningGestureMappings()
     {
         Editor.Pan.Value = new AnyGesture(new MouseGesture(MouseAction.LeftClick));
         Editor.Selection.Apply(SelectionGestures.None);
         Editor.Cutting.Value = MultiGesture.None;
         ItemContainer.Selection.Apply(SelectionGestures.None);
         ItemContainer.Drag.Value = MultiGesture.None;
         Connector.Connect.Value = MultiGesture.None;
     }
 }
```
</details>

Things I need to think about: 
- allow clicking through `ItemContainer` and `Connector` while in panning mode
- pan with scroll wheel

**Comment by jpk6789** [comment]
Hi, what also would be cool to add touch gestures. So for example zooming with two fingers, pan vertical / horizontal with one finger, select a node with one tap,... I tried to implement that but had troubles with selection and pan and had not looked into that any further

**Comment by miroiu** [comment]
I'm currently working on moving the logic of the editor states inside the editor itself and just call those methods with the appropriate parameters from those states. That would make it much easier to control the editor behavior from different input sources.

**Comment by miroiu** [comment]
I found a better solution and created a PR (#167). Now you can just write the following and it will work just fine:
`EditorGestures.Mappings.Editor.Pan.Value = new MouseGesture(MouseAction.LeftClick, Key.Space);`

**Comment by miroiu** [comment]
> Hi, what also would be cool to add touch gestures. So for example zooming with two fingers, pan vertical / horizontal with one finger, select a node with one tap,... I tried to implement that but had troubles with selection and pan and had not looked into that any further

@jpk6789 With PR #170, it should be easier. Subclass the editor and override `OnTouch*` methods, then forward the events to the `InputProcessor`. And implement a custom `IInputHandler` that can handle these events.

I will eventually add these methods in the base editor. I would also like to add support for touchscreen myself but I don't have a display to test with.

**Comment by jpk6789** [comment]
This is really really nice. Thank you for all you effort. I hope, I have some time during the Christmas holidays to look into your code. I will try to implement the touch stuff in a similar way in a PR.

For the touch screen: I have actually bought one of those 15'' mobile USB-C displays with multi-touch last year to have a second screen for my laptop and also to program such touch stuff in DMXControl 3 as well. So I can test that.
