### ISSUE TITLE
[Question] How to implement SmoothStep Connection style on WPF?

### ISSUE THREAD

**Issue by lyq-lin** [miroiu/nodify#148]
Hello,@miroiu!  As described in the title, I would like to discuss how to implement the style of smooth step connection on WPF? Because in similar node editors, I seem to have only seen similar designs on the browser side. After practicing and researching, I found that implementing the smooth step style is extremely troublesome. I would like to know if I will learn how to implement smooth step connection in notify?
![image](https://github.com/user-attachments/assets/e85b701f-c614-42bf-b68b-cfcadf082620)

**Comment by miroiu** [comment]
Hi @lyq-lin ! I implemented the feature in this PR: #149. Please let me know if that works for you.

**Comment by lyq-lin** [comment]
It's amazing that I can always learn the "best practices" of WPF on notify. Thank you for your answer @miroiu
