### ISSUE TITLE
NodifyEditor.SelectionChanged Event always triggered when left mouse button selection a node?

### ISSUE THREAD

**Issue by Yokosama** [miroiu/nodify#15]
Code in Nodify.Calculator, add **SelectionChanged="Editor_SelectionChanged"**
xaml code:
```c# 
 <nodify:NodifyEditor DataContext="{Binding Current}"
                             ItemsSource="{Binding Operations}"
                             Connections="{Binding Connections}"
                             SelectedItems="{Binding SelectedOperations}"
                             ConnectionCompletedCommand="{Binding CreateConnectionCommand}"
                             DisconnectConnectorCommand="{Binding DisconnectConnectorCommand}"
                             Background="{StaticResource SmallGridLinesDrawingBrush}"
                             GridCellSize="15"
                             SelectionChanged="Editor_SelectionChanged"
                             x:Name="Editor">
```
xaml.cs code:
```c#
       private void Editor_SelectionChanged(object sender, System.Windows.Controls.SelectionChangedEventArgs e)
        {
            Debug.WriteLine("Editor_SelectionChanged");
        }
```
![image](https://user-images.githubusercontent.com/19573211/120599435-1908e680-c47a-11eb-9022-da5eef876d3c.png)

Is there a beter way to trigger selection changed event? Thank you.

**Comment by miroiu** [comment]
Hi,
That's indeed an issue, but you can use an observable collection and subscribe to add and remove item events for now.
Example using NodifyObservableCollection:

```csharp
SelectedOperations.WhenAdded(operation =>
{
    Debug.WriteLine("Added to selection " + operation.Title);
}).WhenRemoved(operation =>
{
    Debug.WriteLine("Removed from selection " + operation.Title);
});
```
![image](https://user-images.githubusercontent.com/12727904/120902907-9b94d000-c64b-11eb-9b15-0aa0b308966e.png)

![image](https://user-images.githubusercontent.com/12727904/120902899-933c9500-c64b-11eb-8105-ae88d942178d.png)

**Comment by Yokosama** [comment]
It's really a solution. Thank you very much.

**Comment by miroiu** [comment]
The `SelectionChangedEvent` should work properly now.
