### ISSUE TITLE
[Application]AIRobot: A Workflow Automation Tool Using Nodify Library

### ISSUE THREAD

**Issue by xieyan110** [miroiu/nodify#157]
https://github.com/xieyan110/AIbotot/tree/main/AiRobotUi/AiRobot

I developed this project using the Nodify library. It offers the following capabilities:

 - Mouse and Keyboard Control: The application allows users to manipulate the mouse and keyboard through node-based interactions.
 - Android Device Automation: Utilizes ADB (Android Debug Bridge) to control Android smartphones remotely.
 - Workflow Management: Workflows can be created and saved in JSON format.
 - Workflow Execution: The home interface enables loading workflow lists and executing multiple workflows concurrently.

The project leverages node-based programming to create flexible and visual automation scenarios across different platforms and devices.

**Comment by xieyan110** [comment]
![bf878e60efec43074727edeb4901148](https://github.com/user-attachments/assets/46cdbf80-5c6f-4e7f-8e69-3544b6f1276e)

Initially designed for personal use, so it lacks internationalization

**Comment by miroiu** [comment]
Thanks for sharing your project, it looks really handy! It’s making me think how cool it would be to have a node-based tool for integration testing, so I could test Nodify with Nodify itself 😊. 

Would you mind sharing this in the [Who is using Nodify](https://github.com/miroiu/nodify/discussions/158) discussion? I’m sure others would love to see it there too!

**Comment by xieyan110** [comment]
> Thanks for sharing your project, it looks really handy! It’s making me think how cool it would be to have a node-based tool for integration testing, so I could test Nodify with Nodify itself 😊.
> 
> Would you mind sharing this in the [Who is using Nodify](https://github.com/miroiu/nodify/discussions/158) discussion? I’m sure others would love to see it there too!

Thank you! I'd be happy to share my project in the discussion. 😊
