### ISSUE TITLE
Does GroupingNode need a resize completed event to implement undo resize?

### ISSUE THREAD

**Issue by Yokosama** [miroiu/nodify#16]
Hi, i want to implement undo resize when GroupingNode resize completed. It looks like i need to add an event? or is there any other solution? Thank you.

**Comment by miroiu** [comment]
Hi, you can bind to the GroupingNode.ActualSize property which is only set when the resize is completed.
Example from Playground app:
```xaml
<DataTemplate DataType="{x:Type local:CommentNodeViewModel}">
    <nodify:GroupingNode ActualSize="{Binding Size}"
                         Header="{Binding Title}" />
</DataTemplate>
```

```csharp
private Size _size;
public Size Size
{
    get => _size;
    set => SetProperty(ref _size, value); // you can record the change in here
}
```

Please let me know if that helps.

**Comment by miroiu** [comment]
Added `ResizeCompleted` event and `ResizeCompletedCommand` in commit 12a8d2f20fcd5eba6f2fb53ef570d70545576ea9
Let me know if this is what you need. Thanks!

**Comment by Yokosama** [comment]
Yes, that's what I need. Thank you very much.
