### ISSUE TITLE
[Bug] In Calculator example, connecting a node to the input of another node doesn''t replace the existing connection visually

### ISSUE THREAD

**Issue by pingu2k4** [miroiu/nodify#2]
**Describe the bug**
Say I have an add node, and in the top input I have pi connected. If I have another node, lets say a subtract node, and drag from the subtract output to the top input on add, then logically it replaces the pi node being input (all values now represent the subtract node entering at top input), however the pi node is visually also still connected to that same top input

**To Reproduce**
Drag 3 nodes out. Connect one node to another, and then with the third connect that output to the already used input on one of the other 2 nodes

**Expected behavior**
Visually, the old input gets disconnected

**Screenshots**

**Additional context**
Saw this project from Discord, Will be using it as soon as my base project template is sorted, have a few more things to do. Have an old project in dire need of a V2, and this is perfect for it.

**Comment by miroiu** [comment]
Hi, you described the bug very well and it was easy to reproduce and fix.
The issue will be closed with the commit.
Thank you!
