### ISSUE TITLE
[Question] What is the best way to save all current node state?

### ISSUE THREAD

**Issue by GGorany** [miroiu/nodify#20]
What is the best way to save all current node state?

I'm a beginner in programming, and your project is really helpful to me.
I think you already have in mind,
What's the best way to save and reload all of the current node state?

If you already have a solution, please let me know.

Thank you very much.

**Comment by miroiu** [comment]
Hi,

This is really up to you.

Depending on how you structure the view models, you have a couple of options:

- serialize the whole object graph into JSON/XML/binary or any other format (if there are no cyclic dependencies)
- extract the data that you want to be saved from the view models and serialize it into JSON/XML/binary or any other format (**Recommended**)

Both approaches should give you the possibilty to reconstruct the object graph from the saved data. After that you just have to set the data context to use the new object.

I would suggest you look into https://www.newtonsoft.com/json
