### ISSUE TITLE
[Feature] Generate settings panel from view model

### ISSUE THREAD

**Issue by miroiu** [miroiu/nodify#22]
**Is your feature request related to a problem? Please describe.**
Adding new entries to the Playground's settings panel is error-prone and it's really hard to change their order.

**Describe the solution you'd like**
The settings panel could be generated based on a view model that has a list of available settings.

**Additional context**
The settings panel in Nodify.Playground
![The settings panel](https://user-images.githubusercontent.com/12727904/127170867-c11058ee-79dc-43c8-986b-99da5e1895d2.png)

**Comment by VBerman** [comment]
Is this issue still active? I can take it

**Comment by miroiu** [comment]
Hi! Yes, you can take it.

**Comment by VBerman** [comment]
Hello, is the solution through Reflection suitable for the project?
It remains for me to figure out how to make bindings and place it all in a normal structure
![image](https://user-images.githubusercontent.com/61354229/188320903-aef635b2-2b8e-42ca-862b-052c20339644.png)

**Comment by miroiu** [comment]
Hey, I believe that Reflection would overcomplicate things. The real issue here is the XAML code for the settings panel. To add a new entry at the top (row 0), you'd have to manually offset all the other entries by one row. I think that having all the available settings hardcoded into a list of viewmodels would be enough. That way you could easily change the order of the items inside the list and that would reflect into the view.

**Comment by VBerman** [comment]
Hello, list from Reflection will like sequence in PlaygroundSetting fields. If swap fields in PlaygroundSettings - list too will changed. But okay, I can implement viewmodels for settings, but I have not idea how associate settings from this list with PlaygroundViewModel (how PlaygroundViewModel will take settings? Create a separate method to find the required setting?) 
I implement a way with viewmodels and share this. I apologize for possible stupidity, this is my first experience in such.

**Comment by miroiu** [comment]
One option would be to implement `IEnumerable` in `PlaygroundSettings` and return the hardcoded list of settings (hardcoded inside the constructor most probably). Another option would be to create the list with the hardcoded items inside the `PlaygroundViewModel`'s constructor. In both cases, the `PlaygroundViewModel.Settings` property will have the list of settings which will then be bound to the `<local:EditorSettingsView DataContext={Binding Settings} />` view inside `MainWindow.xaml`.
Now you will have access to the bound settings inside the `EditorSettingsView.xaml` view via `DataContext`.

I hope that helps and feel free to ask any other questions.

**Comment by VBerman** [comment]
Okay, I finally figured it out. 
For each type settings will be created separate VM.
Base class for all them look like:

    public class SettingViewModel : ObservableObject
    {
        public SettingViewModel(string title)
        {
            Title = title;
        }
        public string Title { get; set; }
        protected Control _control = new();
        public Control Control
        {
            get => _control;
        }
    }
Then every type settings will look like:

    public class TextboxSettingViewModel : SettingViewModel
    {
        public TextboxSettingViewModel(string title, double value) : base(title)
        {
            _control = new TextBox();
            _value = value;
            var binding = new Binding("Value") { Source = this };
            _control.SetBinding(TextBox.TextProperty, binding);
        }

        private double _value;

        public double Value
        {
            get { return _value; }
            set { _value = value; }
        }
    }
Bindings tested and working successfully
But I have not idea how take value from settings without downcase. On this moment getting field value looks like that:

    public List<SettingViewModel> Settings { get; set; } = new();
    public MainWindow()
    {
        Settings.Add(new TextboxSettingViewModel("Hello, world", 25));
        // If need get setting need do downcast
        if (Settings[0] is TextboxSettingViewModel)
        {
            double a = (Settings[0] as TextboxSettingViewModel).Value;
        }
    }
I think there is an easier way for get setting, do you have any idea?

**Comment by miroiu** [comment]
You could have a common interface for all the settings like this:

```csharp
public interface ISettingViewModel
{
    string Name { get; }
    string? Description { get; } // This is the tooltip
    object? Value { get; set; }
}
```

The have a base setting class that's type safe:
```csharp
public class BaseSettingViewModel<T> : ObservableObject, ISettingViewModel
{
    public string Name { get; }
    public string? Description { get;  } // This is the tooltip

    private object? _value;
    object? ISettingViewModel.Value
    {
        get => _value;
        set => SetProperty(ref _value, value);
    }

    public T Value
    {
        get => ((ISettingViewModel)this).Value is T val ? val : default!;
        set => ((ISettingViewModel)this).Value = value;
    }

    public BaseSettingViewModel(string name, string? description = default)
    {
        Name = name;
        Description = description;
    }
}
```

And a different sub-class for each data type so you can use `DataTemplate`s to render the view where the value will be bound. (like a TextBox or a CheckBox, etc)

```csharp
public class BoolSettingViewModel : BaseSettingViewModel<bool>
{
    public BoolSettingViewModel(string name, string? description = null) 
        : base(name, description)
    {
    }
}

public class StringSettingViewModel : BaseSettingViewModel<string>
{
    public StringSettingViewModel(string name, string? description = null) 
        : base(name, description)
    {
    }
}
```

Then you can still have a list of settings and you don't need to cast each instance to a specific type in order to access the `Value` property because that's available on the interface:
```csharp`
public List<ISettingViewModel> Settings { get; } = new List<ISettingViewModel>();
``

**Comment by miroiu** [comment]
Doing this will probably work just fine but then how would you bind the settings to the editor? I think we could use the `EditorSettings` to do that for us and create a proxy setting that would just set properties on the `EditorSettings` instance.

Something like this:
```csharp
    public class ProxySettingViewModel<T> : BaseSettingViewModel<T>
    {
        private readonly Func<T> _getter;
        private readonly Action<T> _setter;

        public ProxySettingViewModel(Func<T> getter, Action<T> setter, string name, string? description = default)
            : base(name, description)
        {
            _getter = getter;
            _setter = setter;
        }

        public new T Value
        {
            get => _getter();
            set => _setter(value);
        }
    }
```

And you could use it like this:
```csharp
 new ProxySettingViewModel<double>(
                () => EditorSettings.Instance.AutoPanningTickRate,
                val => EditorSettings.Instance.AutoPanningTickRate = val,
                "Auto panning tickrate")
```

**Comment by VBerman** [comment]
Wow, it is next level for me :D 
I'm implement this, thank you for your attention. 
It's a great experience for me

**Comment by miroiu** [comment]
Hi @VBerman! Are you still working on this? If not, I will unassign it so others can pick it up. Thanks!

**Comment by miroiu** [comment]
Unassigned due to inactivity.

**Comment by VNDPAL** [comment]
is this feature still needed? If yes then is anyone working on it?

**Comment by miroiu** [comment]
Yes, it's still needed. I don't think anyone is working on it. It seems to be a little bit difficult. Do you want to give it a try?

**Comment by Riju-bak** [comment]
Hi Miroiu, I see that this issue is still open. If it hasn't been assigned to anyone else can I give it a try?

**Comment by miroiu** [comment]
Hi @Riju-bak , I'd be happy if you give it a try.

**Comment by Riju-bak** [comment]
Cool, I have already started. I'll share more details once I get something substantial done.

**Comment by Riju-bak** [comment]
@miroiu So I basically went with your suggestion in the comments above.

We can now hardcode settings in the PlaygroundSetting.cs constructor and it will get reflected in the View. I'm using DataTemplate.Triggers to render the correct component based on data-type. Example: Textbox for uint and Checkbox for bool.

However, the triggers aren't getting triggered.

See PlaygroundSettingsView.xaml  in [Settings Panel from ViewModel](https://github.com/miroiu/nodify/pull/62)

I'm trying to fix this at the moment. Perhaps you could tell me what I'm doing wrong. 
Apologies in advance, WPF is new to me.

**Comment by Riju-bak** [comment]
Alright, I'll try this out day after tomorrow.

**Comment by miroiu** [comment]
Thank you very much @Riju-bak for fixing this issue!

**Comment by Riju-bak** [comment]
> Thank you very much @Riju-bak for fixing this issue!

You're welcome @miroiu . 
Also, this was my first open source contribution, so I'm feeling really good about this. :)
