### ISSUE TITLE
[Feature] Different shapes and colors of connectors. Also: Only connect matching connectors

### ISSUE THREAD

**Issue by Megapit** [miroiu/nodify#27]
**Is your feature request related to a problem? Please describe.**

I plan to renew my feeder for vJoy and release this as open source. vJoy is a virtual gaming device which is controlled by a so called feeder. For Example there is [Joystick Gremlin](https://whitemagic.github.io/JoystickGremlin/) 
I allready have my own, fully working feeder which i did not release because of the complex configuration i have done. Joystick Gremlin is till now easier :)
NodeRed like virtual programming seems a good solution for such a configuration task.
While seaching for a NodeRed like programming interface for c# i come to nodify, which is by the way a very cool project.

The only thing what is missing to me is to use different shaped and colored connectors. 

Let me explain why:
I want that the user can only connect bool outputs to bool inputs, POV outputs to POV inputs and Axis outputs to Axis inputs. Converting between them should be done in different nodes.
So the user should see which connectors can be connected on the shape (or the color) of the connector.

**Describe the solution you'd like**
For me it would be enought to have the circle shape, a recangle shape and a triangle shape for an connector and only allow connections with the same type.

But i know this is only my need. So i would suggest to implement a system which can be used by other programmers. 
For example an property in the connector which is defining its shape and another property whis is defining its color. But this will be override theming. I know :( Any solutions in mind for that?

Also i suggest another property in the connector which define to which other connector it can be connected. For example: the output connector has an int property with the value 2. The input connector in this example has this property set to 3. A bitwise AND is bigger then zero so this two connectors can be connected.
Second example: output connector property is 2 and input connector is 1. Bitwise AND is 0, so this two connectors can not match.

The color of a connection of two matching connectors  should be the color the output connector.

**Describe alternatives you've considered**
I hope i made it clear in my solution. If not ask.

**Additional context**
I don't have any exaple pictures yet

**Comment by miroiu** [comment]
Hi @Megapit,

The feature you requested can be achieved with the existing functionality.
I created a PR to demonstrate that.

Please let me know if I'm missing anything.
