### ISSUE TITLE
[Bug] Connections do not render correctly in TabControl

### ISSUE THREAD

**Issue by Erranaxx** [miroiu/nodify#3]
Firstly, thank you immensely for the project, this library will be used as part of an internal tool that produces Lua scripts from a node graph. It has many of my colleagues quite excited!

**Describe the bug**
The connection lines fail to render / update their positions correctly when the NodifyEditor is parented by a TabControl.

**To Reproduce**
My scenario is relatively complicated as I'm using a fork of the Avalon Dock but I have managed to reproduce it in a simpler manner.

1. Using your calculator example has a base, replace the NodifyEditor in the MainWindow with the following (reusing the same DataContext does not appear to have any affect as the bug is still present):
```
<TabControl>
  <TabItem Header="Tab 1">
    <nodify:NodifyEditor ... />
  </TabItem>
  <TabItem Header="Tab 2">
    <nodify:NodifyEditor ... />
  </TabItem>
</TabControl>
```
2. Run the project.
3. Add 2 nodes the the node graph (in Tab 1) and make a connection between them.
4. Switch to Tab 2, we are sharing a DataContext so the nodes we added in Tab 1 will appear. You can correctly move a node in this graph and the connection will adjust correctly.
5. Switch back to Tab 1. The connection now stays in place and does not update when either node is moved.

**Expected behavior**
The connections should continue to render / update when switching tabs.

Please let me know if there's any additional information I could provide to help reproduce the issue. Thanks again!

**Comment by miroiu** [comment]
Hi, it's nice to hear that this project is being used in great tools!

I was able to reproduce your bug pretty easy and the fix was just one line of code (one variable assignment).
The issue will be closed automatically with the next commit.

Thanks for reporting the bug.
