### ISSUE TITLE
WolvenKit for modding CyberPunk 2077

### ISSUE THREAD

**Issue by ruchirlives** [miroiu/nodify#31]
Hi miroiu 

The devs of WolvenKit are exploring implementing Nodify as a node based component for the open sourced application.
It’s a modding application for Cyberpunk 2077 and similar RED engine based games.
While the user base for this application is in the several 1000s, and very active, the devs are all volunteers. Keen to reach out and see if you could advise/support us?
See https://github.com/WolvenKit

**Comment by miroiu** [comment]
Hi, ruchirlives,

WolvenKit looks like a big project and because I am really busy nowadays I'd rather not get involved in anything of this size. Have a great day!

**Comment by ruchirlives** [comment]
No probs
I think the wolvenkit team were doing some amazing work with help from your code. I've not been keeping tabs for a couple of months.

Ruchir
________________________________
