### ISSUE TITLE
[Feature]Is there an easy way to create a graph mini map?

### ISSUE THREAD

**Issue by Yokosama** [miroiu/nodify#32]
Like this:
![image](https://user-images.githubusercontent.com/19573211/161957815-6684d675-8339-4651-b366-e625b7f01cbe.png)

My solution：
https://gist.github.com/Yokosama/723b0465a669c9207b69b77e9cec653d
![xxx](https://user-images.githubusercontent.com/19573211/162166702-5c08a4a6-1f1f-4b7b-b114-2ffdc3dc1811.png)

I have some question:
How to get ItemContainer's width and height use binding? the result I got was Nan.
The ItemContainer's location are not updated until the drag is completed, how to update minimap's node items location in realtime when drag node item? 

So, is there a better solution, thank you very much.

**Comment by miroiu** [comment]
Set NodifyEditor.EnableDraggingContainersOptimizations to be false to receive real-time ItemContainer.Location updates.

**Comment by miroiu** [comment]
This is now implemented by #124
