### ISSUE TITLE
[Bug] Connections can be created cross graphs

### ISSUE THREAD

**Issue by miroiu** [miroiu/nodify#37]
**Describe the bug**
It is possible to connect nodes to child graphs, which is not intended and will result in bad Anchor calculations.

**To Reproduce**
Add an operation graph in the calculator example and connect a node from the root graph to another node inside the operation graph.

**Expected behavior**
I should not be able to create connections across graphs.

**Screenshots**
In this example, the output of the Add node is connected to the input of the Output parameters nodes inside the Operations graph.

![image](https://user-images.githubusercontent.com/12727904/179273980-c9b77879-9c28-4cfd-96ec-714cfab3d5b6.png)

**Comment by AnvarAslam** [comment]
Can I Solve These Issue

**Comment by miroiu** [comment]
Hi @AnvarAslam! You can solve it! Please let me know if you need more information.

**Comment by AnvarAslam** [comment]
@miroiu give me all info plz  about this project what the bug you face and guide me to solve

**Comment by AnvarAslam** [comment]
i am little bit confuse can u help to get started

**Comment by miroiu** [comment]
You can start by looking at what the PendingConnection does.

**Comment by miroiu** [comment]
Hi! I fixed this issue for the v4.0.0 release.
