### ISSUE TITLE
[Question] Is it possible to snap selection rectangle

### ISSUE THREAD

**Issue by wrekklol** [miroiu/nodify#39]
Hello. I was wondering if it is possible to make the selection rectangle snap to the/a grid? Doing an image editor currently, and I'm trying to get it to snap to the pixels but it seems like it is not possible currently? Not that experienced with WPF yet. :)

Also, is it possible to use the selection as a dependencyobject? I'm trying to do marching ants on the selection as well.

**Comment by wrekklol** [comment]
Got the first thing working by setting UseLayoutRounding on the selection style. Now I'm just trying to figure out how to use animations on it.

**Comment by miroiu** [comment]
Hi! Your use case is interesting but I'm not sure how much of Nodify you can use for an image editor.
It is not possible to snap the selection rectangle to the grid at the moment. And as you may already have figured out, you can override the selection rectangle style to implement marching ants. (I created a [PR](https://github.com/miroiu/nodify/pull/40) to demonstrate that)

**Comment by wrekklol** [comment]
The graph editor is what I use Nodify for currently, because it "just works". :)

**Comment by miroiu** [comment]
That's really cool! I am curious what package version you use. There are a lot of improvements in v2 but it has many breaking changes. I created a changelog for that.

**Comment by wrekklol** [comment]
I'm using the master branch from about 3 weeks ago. :)
