### ISSUE TITLE
[Feature] Add multiple tabs to the calculator app

### ISSUE THREAD

**Issue by miroiu** [miroiu/nodify#4]
**Is your feature request related to a problem? Please describe.**
It would be good to have an example of how to use multiple editors in an application.

**Describe the solution you'd like**
Use a tab control with a 'plus' button like in Chrome to create a new tab. The new tab will contain an empty editor instance.

**Optional** 
Add a way to close the tabs. Suggestions:
- a 'close' button present in each tab
- a key-binding like CTRL+W 
- a context menu with a close command

**Comment by RajaduraiAz** [comment]
Hi @miroiu i would like to work on this

**Comment by miroiu** [comment]
Hi @RajaduraiAz!
That's great. Please let me know if you have any questions.

**Comment by RajaduraiAz** [comment]
@miroiu great I am started to work on this
