### ISSUE TITLE
[Feature] Configurable arrowhead for connections

### ISSUE THREAD

**Issue by miroiu** [miroiu/nodify#44]
**Describe the solution you'd like**

The `BaseConnection` can display an arrowhead at the end of the line if `ArrowSize` is valid. I would like to be able to specify at which end of the line the arrow should be displayed. (possible values for ArrowHeadEnds: None, Start, End, Both).

Don't forget to add the new setting to the Playground app.

Optional: Customize the shape of the arrowhead: Arrow (default), Ellipse, Rectangle

**Comment by AnvarAslam** [comment]
Can I Solve These Issue & U Can Guide Me To Solve It

**Comment by miroiu** [comment]
Hi @AnvarAslam! You already have #37 assigned to you. Once you solve that one you can also pick this one unless someone else starts working on it.

**Comment by vinicius-nicolete** [comment]
Hello @miroiu , can I work in this issue?

**Comment by miroiu** [comment]
Hi @vinicius-nicolete ! Sure, you can have it.

**Comment by vinicius-nicolete** [comment]
Hi @miroiu, 
I have some trouble for testing.
I can test in the Playground project, right? There need to be create a setting or already have a setting there for doing that?
 
![image](https://user-images.githubusercontent.com/73319683/198753762-9d455872-d26e-4e69-943c-9268447a0e0a.png)

**Comment by miroiu** [comment]
Hi @vinicius-nicolete, you have to add a new setting in the playground app for the arrowhead.

**Comment by miroiu** [comment]
Just to add some information here: the BaseConnection class is the place to add the arrowhead. There is the DrawArrowGeometry method that can be used to draw the arrow in the correct position. This method already knows how to draw the arrowhead on each end of the line depending on the Direction property. The direction only switches the meaning of the ArrowHeadEnds.Start and ArrowHeadEnds.End and should be fairly easy to implement. I think that ArrowHeadEnds.Both can be implemented by calling GetArrowHeadPoints again with the target and source reversed.

**Comment by mshumayl** [comment]
Hi @miroiu, if it's okay, I'd like to work on this.

**Comment by miroiu** [comment]
Hi @mshumayl, you can have it!

**Comment by miroiu** [comment]
Hi @mshumayl ! Thank you very much for your contribution.
