### ISSUE TITLE
Examples don't work with nuget packages

### ISSUE THREAD

**Issue by randym32** [miroiu/nodify#5]
**Describe the bug**
When I try to build the examples, using the nuget package -- rather than a local build of the nodify csproj -- I get many xaml namespace errors.  Reading the change log this appears to be from the repository having been updated since the last nuget package release to provide the namespace support.

**Requested Fix**
I'd like to ask for a new nuget package release.  Thank-you!

**Comment by miroiu** [comment]
Hi, 

I will create a new release as soon as possible. 
Thanks for reporting!

**Comment by miroiu** [comment]
New versions is up: https://www.nuget.org/packages/Nodify/1.6.1
