### ISSUE TITLE
[Question] Bring the selected node on top?

### ISSUE THREAD

**Issue by trrahul** [miroiu/nodify#57]
Hi. Is it possible to bring the selected node on top? Currently the last added node comes on top of all other nodes and if you select others they are behind the last added one.

**Comment by miroiu** [comment]
Hi! Yes, it is possible. Here's an example:

```xaml
<nodify:NodifyEditor.ItemContainerStyle>
    <Style TargetType="{x:Type nodify:ItemContainer}"
           BasedOn="{StaticResource {x:Type nodify:ItemContainer}}">
        <Style.Triggers>
            <Trigger Property="IsSelected" Value="True">
                <Setter Property="Panel.ZIndex" Value="1" />
            </Trigger>
        </Style.Triggers>
    </Style>
</nodify:NodifyEditor.ItemContainerStyle>
```

![bringtofront](https://user-images.githubusercontent.com/12727904/230344477-145139c5-fe88-4e4f-8a6d-76725276aeb4.gif)

I'll also add this to be the default for the Playground app.

**Comment by trrahul** [comment]
Thanks for the quick answer. I tired the code, and it worked.
