### ISSUE TITLE
Hierarchical graph layout

### ISSUE THREAD

**Issue by GeorgeS2019** [miroiu/nodify#6]
=> just saw [Group Node](https://github.com/miroiu/nodify/wiki/Nodes-Overview#2-the-groupingnode-control) after suggesting this.

![Grouping Node](https://i.imgur.com/HYxt2cs.gif)

**Describe the solution you'd like**
When the number of nodes getting too many, it would make sense to group them into groups each represented by a SINGLE [Group Node](https://github.com/miroiu/nodify/wiki/Nodes-Overview#2-the-groupingnode-control) **BUT same size has single Non-group node.** When click on it, it expands OR a side window appears, showing the nodes layout of the nodes within the clicked module.

![image](https://user-images.githubusercontent.com/49812372/113505825-88795d00-9541-11eb-804b-cb6fcb2abfa8.png)

Excellent work!!!

**Comment by miroiu** [comment]
Hi!
 Is the Grouping Node what you are looking for? 

Thanks for contributing!

**Comment by GeorgeS2019** [comment]
@miroiu 
I see lot of potential of your work. 
- ideally we need some sort of hierarchical layout algorithm from Graphivz involving your existing **Grouping Node**
- Even better (for me) is to encapsulate the Grouping Node into ONE single Node, without seeing the child nodes. To hide complexity of Grouping Node. So we can present HIGH level view of the workflow, without seeing the individual nodes but encapsulating parent "group" nodes.

**Comment by GeorgeS2019** [comment]
@miroiu 
I see lot of potential of your work. 
- ideally we need some sort of hierarchical layout algorithm from Graphivz involving your existing **Grouping Node**
- Even better (for me) is to encapsulate the Grouping Node into ONE single Node, without seeing the child nodes. To hide the complexity and larger size of Grouping Node. So we can present HIGH level view of the workflow, without seeing the individual nodes but encapsulating parent "group" nodes.

**Comment by GeorgeS2019** [comment]
@miroiu 
I see lot of potential of your work. 
- ideally we need some sort of hierarchical layout algorithm from Graphivz involving your existing **Grouping Node**
- Even better (for me) is to encapsulate the Grouping Node into ONE single Node, without seeing the child nodes. To hide the complexity of Grouping Node. So we can present HIGH level view of the workflow, without seeing the individual nodes but encapsulating parent "group" nodes.

**Comment by miroiu** [comment]
@GeorgeS2019  

A general idea would be to move the group of nodes into another graph and have a node that links to it (similar to how Unreal Engine does it when [collapsing graphs](https://docs.unrealengine.com/en-US/ProgrammingAndScripting/Blueprints/BP_HowTo/CollapsingGraphs/index.html))

This can be achieved with the current features and a good viewmodel hierarchy.

**Comment by miroiu** [comment]
@GeorgeS2019 

I've added an example of a node that can hold a graph inside. (see Calculator app)
I hope this helps!

**Comment by GeorgeS2019** [comment]
@miroiu I know, U are faster than I can check and then make suggestions :-)

**Comment by miroiu** [comment]
Hi @GeorgeS2019, is there anything else you'd like to know or can I close this issue?

**Comment by GeorgeS2019** [comment]
@miroiu HI I just checked, the new calculator node is a group node. Fantastic!!!  Thank you

**Comment by GeorgeS2019** [comment]
@miroiu  Just had another idea. 

Is it possible to use the group node, in addition to move a group of nodes, the group node can collapse the nodes within its container into a single "Group Node" 

This collapsing only works in these nodes have incoming and outcoming connections. 

Do you think this is possible?

**Comment by miroiu** [comment]
@GeorgeS2019 I can't picture that in my mind. Do you mean something like this?

 ![Collapse](https://i.imgur.com/umcFcyf.gif)

You could use the nodes from inside the GroupNode of course, instead of selecting and then collapsing the selection. But for this, you need to filter the nodes that have the Location inside the group node because the group node doesn't know what nodes overlap with it.

**Comment by GeorgeS2019** [comment]
@miroiu You have done a lot RIGHT.  Yes.  It is more just usability. The approach I suggest only make sense after layout is implemented. So that once the group NODE is created out of a few nodes, the layout automatically apply and a simpler view of the nodes is presented to provide an update of the node hierachy for further analysis.

**Comment by miroiu** [comment]
@GeorgeS2019 Have you considered this approach?

![Graphs](https://i.imgur.com/dY7rje8.gif)

It's not working out of the box but could be done with minor modifications.

**Comment by GeorgeS2019** [comment]
@miroiu  As I said, U done a lot!!  However, what you offer, is considered RARE among .NET community.  If you like to address this unmet .NET community need.

Take time...  there are many unmet use cases.

(1) As u suggest above, it is a very Unique solution.  Not sure I have found elsewhere.  => Ideally, after once has done with the layout, one can collapse the group container node to back to a SINGLE node same size as others

(2) The other use case is a hierarchical state machine (U have provided a non hierarchical state machine, how about a hierachical one that looks like the picture others use?

![image](https://user-images.githubusercontent.com/49812372/114559225-cb3ae380-9c6b-11eb-94c9-4c19b69efbcc.png)

![image](https://user-images.githubusercontent.com/49812372/114559306-e0177700-9c6b-11eb-87bb-e143ca3dd683.png)

**Comment by GeorgeS2019** [comment]
@miroiu  As I said above.. What u have contributed will inspire others!! thank you!

**Comment by miroiu** [comment]
@GeorgeS2019 No worries, if you really like this project, please give it a star ⭐

I'm pretty sure you can achieve what you need with a bit of effort.

I made the Grouping Node collapsible but you won't be able to connect nodes directly from outside. Is this how you imagined it?

![Collapse](https://i.imgur.com/m4wRejO.gif)

**Comment by GeorgeS2019** [comment]
@miroiu   Everything is excellent, I will promote this project :-)

**Comment by GeorgeS2019** [comment]
@miroiu  [Can u address the questions suggested here](https://github.com/imjp94/gd-YAFSM/issues/19#issuecomment-829903042)? This is another use case where Nodify will have an impact!

**Comment by GeorgeS2019** [comment]
@miroiu 

> Btw, UI of nodify looks really good, it can be a great source of inspiration for the upcoming UI improvement for YAFSM.

[Source](https://github.com/imjp94/gd-YAFSM/issues/19#issuecomment-829903042)

**Comment by miroiu** [comment]
Hi @GeorgeS2019, thanks for finding some real use cases for Nodify. All of these open-source projects are a good fit for Nodify but I'd rather invest the time working on Nodify than starting big projects like creating a brand new editor.

Thanks for your interest!
