### ISSUE TITLE
Text on Lines

### ISSUE THREAD

**Issue by mercurial-moon** [miroiu/nodify#63]
Hi ,
Is it possible to insert text on the connecting lines between nodes?
I didn't see any preview of this feature in the demos that have been showcased.
Would  it be too difficult to implement this, if its not implemented yet, could you let me know what part of the code needs to be modified to implement this feature?

**Comment by miroiu** [comment]
Hi, this functionality is not implemented. However, it is possible to add a label to connection lines by adding a formatted text to the DefiningGeometry in BaseConnection. (see https://stackoverflow.com/questions/4180958/add-some-text-in-a-wpf-shape)

For an editable label you'd have to set the ConnectionTemplate in a NodifyEditor instance to a custom DataTemplate and figure out how to position the textbox on the line (probably inside a Canvas). Note that this solution may impact performance when rendering many lines.

Please let me know if you need more information.

**Comment by miroiu** [comment]
Hi, I created a PR to address this issue in case you still need the functionality.
