### ISSUE TITLE
[Question] Blurry text when zoom in, how to prevent that happen?

### ISSUE THREAD

**Issue by KaivnD** [miroiu/nodify#65]
Hi everyone! this is what I'm talking about.

![dwx0TY6OBj](https://github.com/miroiu/nodify/assets/37983330/ac581e5b-7f0a-44e2-912e-8005d7a45cb3)

**Comment by miroiu** [comment]
Hi! The nodes are rendered to a bitmap and the `RenderAtScale` was set to a constant value, and when you increased the `MaxZoom` over that value you got blurry text. I changed it to render at `MaxZoom` by default. 
Note that you can remove the `CacheMode` altoghether if you don't have a large amount of nodes in your own app, or performance problems.

**Comment by KaivnD** [comment]
Second thought, may be this is not a problem after all. It's a trade off, if I want better render results, I will not get better performance.
