### ISSUE TITLE
[Question]How to change the border color of Node

### ISSUE THREAD

**Issue by MakesYT** [miroiu/nodify#69]
![image](https://github.com/miroiu/nodify/assets/42534870/48ee97dd-6d4a-4bb6-bc5a-7dc80ef0c6d9)
![image](https://github.com/miroiu/nodify/assets/42534870/3116ec42-d538-4bd9-939f-f8d2cd008357)
How can I change the border color when it is selected and when it is not selected? I tried to change the resource dictionary but it did not work

**Comment by miroiu** [comment]
Hi, try setting the `SelectedBrush` of the `ItemContainer`

**Comment by MakesYT** [comment]
> Hi, try setting the `SelectedBrush` of the `ItemContainer`
tks,But I actually want to use the viewModel properties to set a different border color for each Node. Is that possible?

**Comment by MakesYT** [comment]
![image](https://github.com/miroiu/nodify/assets/42534870/de276a63-dc04-4ed6-af81-c23a6b9639c5)
i try this,but there is no color in the selection.
Converter works properly

**Comment by miroiu** [comment]
It's definitely possible. One option is to use a `DataTrigger`.

**Comment by MakesYT** [comment]
is working ,tks a lot
