### ISSUE TITLE
[Question] Connection Behind Grouping Nodes

### ISSUE THREAD

**Issue by Captain-Bubble** [miroiu/nodify#71]
Hi! 
First of all: Thanks for Sharing this Awesome Node Editor!!!

Now to the question:

Somehow i Cant get the Connection to be above a Group-node.
As soon as i add a Group i Cant hover over a connection to disconnect it with ALT+Click.

This behavior is in the Playground example by grouping some nodes together and connecting them.

I know, there is an option to display all Connections on Top, but then the Connections are above every Node,
which can look weird in some cases.

Is there a way to get the connection "between" the Grouping nodes and the other nodes?

**Comment by miroiu** [comment]
Hi, 

Unfortunately, it isn't possible because the GroupingNode lives in the nodes Panel which is a different Panel than the connections. And changing its ZIndex only applies to the containing Panel.

**Comment by miroiu** [comment]
While still not possible to show connections in-between nodes, new improvements were made to the `GroupingNode`. One of them is the `IsContentHitTestVisible` dependency property that allows clicking through the content area so connections behind grouping nodes can be selected (see #267).
