### ISSUE TITLE
[Question] Sorting the graph

### ISSUE THREAD

**Issue by CallumCarmicheal** [miroiu/nodify#73]
Hello I am using this project to generate a node graph of function calls in a C# project. Being that all the code is generated and not manually created by the user I was wondering if there is a simple way to sort / organise the nodes like in a Code Map where you can align everything from Left -> Right or Top -> Bottom etc. 

Like this example from Visual Studio's Code Map.
![image](https://github.com/miroiu/nodify/assets/6545688/c831e9c6-eb5c-484d-a348-1393ff94f324)

**Comment by miroiu** [comment]
Hi, it is possible to sort the graph, but it's not built in. You have access to the node's location, size and connections depending on the shape of your view-models. 

However, if you'd like to do this in the view, you don't have access to the connections. 

You can check the state machine example. It has an Alignment option for the current selection in the context menu. That's built in into Nodify as a command.

**Comment by miroiu** [comment]
Closing as not planned. Please feel free to reopen if you need more information.
