### ISSUE TITLE
I want to hide Pending Connection content until it's hover to invalid connection, How can I?

### ISSUE THREAD

**Issue by ankitsatapara07** [miroiu/nodify#76]
Hi @miroiu 

I am not sure weather it is possible or not, but I wanted to hide content of pending connection until it's hover to invalid connection.
What I want is, I don't want to display the pending connection content "Drop on connector",

<img width="385" alt="Screenshot 2023-10-13 202309" src="https://github.com/miroiu/nodify/assets/50800588/7a2f4bfd-ec5a-49e4-9605-3f3183b760cb">

If it's hover to invalid connector it should display the content as shown below.

<img width="361" alt="Screenshot 2023-10-13 202348" src="https://github.com/miroiu/nodify/assets/50800588/7dde4313-ac44-4ad7-9cb0-dff658cdf529">

Any thoughts how to achieve this?

Thanks Again
Have a wonderfull day

**Comment by miroiu** [comment]
Hi, did you try to change the visibility of the content with a DaraTrigger?

**Comment by ankitsatapara07** [comment]
I tried but not working, I am not sure, I am new to WPF and MVVM so I might be doing wrong, 
Please suggest some boilerplate code if this is wrong.
Thanks for your patience.

<img width="614" alt="image" src="https://github.com/miroiu/nodify/assets/50800588/959a25d0-afd2-4cd4-a374-3d6bcb8066be">

If I remove the style for content (It's giving build error so I have to remove), After removing it's somewhat working as expected, but still I am seeing a empty square box which looks somewhat weird.

<img width="353" alt="image" src="https://github.com/miroiu/nodify/assets/50800588/86f195e9-ea57-4b86-9638-191c6ffdb781">

**Comment by ankitsatapara07** [comment]
@miroiu 
Did you get a chance to look into it?

**Comment by miroiu** [comment]
@ankitsatapara07 I updated the playground app with an example on how to do it

**Comment by miroiu** [comment]
I hope that helps.

**Comment by ankitsatapara07** [comment]
@miroiu 
I just see the fix and the updated playground example.
Thank you so much for helping me.
Thanks again 👍
