### ISSUE TITLE
[Question] How do you change the theme during runtime?

### ISSUE THREAD

**Issue by hailstorm75** [miroiu/nodify#84]
I wish to change the theme of the whole application during runtime. The UI components vendor I'm using offers such a feature; however, I could not find anything like that for Nodify.

Is it implemented? If so, where do I find it and how do I use it?

**Comment by miroiu** [comment]
Hi, changing the theme at runtime is not built into Nodify, but all the example apps have this capability. You can see how this is implemented in the shared [ThemeManager](https://github.com/miroiu/nodify/blob/master/Examples/Nodify.Shared/ThemeManager.cs).

![theme](https://github.com/miroiu/nodify/assets/12727904/7f8bf1fa-d491-44f5-8087-3dab839feb97)

**Comment by hailstorm75** [comment]
Fantastic, thank you! Once I try this, I shall close the task.
