### ISSUE TITLE
[Application] Avalonia refactoring version

### ISSUE THREAD

**Issue by MakesYT** [miroiu/nodify#85]
**Describe the application**
Hi, I open source on github and I refactor Nodify using AvaloniaUI, it is currently in the early stages and would like some help
[Nodify.Avalonia](https://github.com/MakesYT/Nodify.Avalonia)
**Screenshots**
![image](https://github.com/miroiu/nodify/assets/42534870/de1ab992-7f59-4941-993d-4532a18b32a6)

**Additional context**
Add any other context here.

**Comment by miroiu** [comment]
Hi! This is cool. What can I help you with?

**Comment by MakesYT** [comment]
groupingNode doesn't seem to have any storage?

**Comment by miroiu** [comment]
GroupingNode tells the editor to select the nodes inside its area when it is selected. This way when we don't move the GroupingNode alone, but the entire selection. Of course, you can come up with a better idea.

**Comment by miroiu** [comment]
Hi @MakesYT, thank you for all your effort! I want to let you know that there is now a recommended Avalonia port that tries to stay as close as possible to this code base and it has all the features the WPF version has. You can check it out here: https://github.com/BAndysc/nodify-avalonia

I will close the issue for now. Please feel free to reopen it in case you need more information.
