### ISSUE TITLE
[Bug] set FlowDirection property of Node, the connection of this Node will not update 

### ISSUE THREAD

**Issue by SunQianchuan** [miroiu/nodify#91]
Hi  miroiu,

i need use FlowDirection  property  to set Node Direction, after i set FlowDirection to RightToLeft, the connection of this Node will not re-render.

Thanks

**Comment by miroiu** [comment]
Hi, try setting FlowDirection on the NodifyEditor, not on individual nodes.

**Comment by miroiu** [comment]
Hi SunQianchuan,

You can achieve all of the following combinations by setting the `ArrowEnds` of the connection to the correct value.

![image](https://github.com/miroiu/nodify/assets/12727904/7c3b898d-671d-4bf1-a83c-654f6ce008c0)

Notice that connection also has a `Direction` property, but that may not be what you want.

**Comment by SunQianchuan** [comment]
Hi miroiu,

Thanks for the suggestion.
I can achieve what I need by swapping Input and Output of Node, and using Direction of connection.

Thanks
