### ISSUE TITLE
[Question]  How to make the line above the node

### ISSUE THREAD

**Issue by heying0122** [miroiu/nodify#92]
like this:  https://user-images.githubusercontent.com/12727904/192101959-2cb9a837-1642-4e96-b2ef-eea5502a587f.png

**Comment by heying0122** [comment]
https://user-images.githubusercontent.com/12727904/192101959-2cb9a837-1642-4e96-b2ef-eea5502a587f.png

**Comment by miroiu** [comment]
Hi! Set `DisplayConnectionsOnTop` to true on the `NodifyEditor` instance.
