### ISSUE TITLE
[Docs] Dead links in contributing doc

### ISSUE THREAD

**Issue by brandonxu360** [miroiu/nodify#94]
**Describe the issue**
Several dead links exist in the contributing doc - specifically, those pointing to documentation and showcase links (https://miroiu.github.io/nodify/docs and https://miroiu.github.io/nodify/showcase/ respectively). 

**Screenshots**
![image](https://github.com/miroiu/nodify/assets/76601710/60d0dbff-9969-4932-b157-533964b23224)

**Additional context**
Dead links were mentioned previously but never resolved (https://github.com/miroiu/nodify/pull/74).

**Comment by miroiu** [comment]
Thanks for your contribution!
